### ISSUE TITLE
Bug no metodo loadMorePosts

### ISSUE THREAD

**Issue by dehlferreira** [johnnycfg/desafio01-trilha-reactjs-space-traveling#2]
Boa noite Johnny, tudo bem?

Cara estou aqui ainda resolvendo o desafio, e quando empaco em alguma coisa eu venho dar uma olhada no seu código rsrsrs.
Mais vi que o método que você criou para a paginação tem um bugzinho.
Quando colocamos o pageSize do prismic para mais de um item por página(ex: pageSize: 2), o método só está retornando o primeiro item da segunda paginação.

Sendo assim eu corrigi no meu projeto, e estou te enviando a forma que fiz para poder listar todos os itens da próxima página.

Qualquer coisa me chama no discord, que explico melhor.

E mais uma vez obrigado pela ajuda.

https://github.com/johnnycfg/desafio01-trilha-reactjs-space-traveling/blob/e2cf418005c897a21b1d2269687c8c2b9c158714/src/pages/index.tsx#L36

````

const loadMorePosts = () => {
    if (!nextPage) {
      return;
    }

    fetch(nextPage)
      .then(response => {
        return response.json();
      })
      .then(data => {
        const newPosts = data.results.map(d => {
          return {
            slug: d.uid,
            first_publication_date: d.first_publication_date,
            data: {
              title: d.data.title,
              subtitle: d.data.subtitle,
              author: d.data.author,
            },
          };
        });

        setPosts([...posts, ...newPosts);

        setNextPage(data.next_page);
      });
  };
````

**Comment by johnnycfg** [comment]
Boa noite André, tudo bem?

Fico feliz que posso ter te ajudado no desafio :). 

Quanto ao bug, de fato eu fiz de forma que atendesse à apenas 1 item por página. Fiz as correções baseado na sua solução e agora responderá bem à mudança do pageSize, agradeço o feedback :).
